# Versi API Kubernetes v1 untuk jenis objek Service
apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
  labels:
    app: karsajobs
# Membuat jaringan NodePort yang dapat diakses host
spec:
  ports:
  - port: 8080
  selector:
    tier: backend
  type: NodePort
