version: 2.1
orbs:
  docker: circleci/docker@2.2.0
# Define the jobs we want to run for this project
jobs:
  lint-dockerfile:
    executor: docker/hadolint
    steps:
      - checkout
      - docker/hadolint:
          dockerfiles: Dockerfile
  test-app:
    docker:
      - image: cimg/go:1.19.4
    steps:
      - checkout
      - run: |
          "cd /go/src/github.com/dicodingacademy/karsajobs/go/src/github.com/dicodingacademy/karsajobs"
          "go test -v -short --count=1 $(go list ./...)"
  build-app-karsajobs:
    executor: docker/docker
    steps:
      - checkout
      - run: |
          echo $CR_PAT | docker login ghcr.io -u ffrmns --password-stdin
          chmod +x build_push_image_karsajobs.sh
          ./build_push_image_karsajobs.sh

# Orchestrate our job run sequence
workflows:
  lint-dockerfile:
    jobs:
      - lint-dockerfile
  test-app:
    jobs:
      - test-app
  build-app-karsajobs:
    jobs:
      - build-app-karsajobs