# Versi API Kubernetes v1 untuk jenis objek Service
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: karsajobs
# Membuat jaringan NodePort yang dapat diakses host
spec:
  ports:
  - port: 27017
  selector:
    app: karsajobs
    tier: database
